language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-x86-google_apis-26

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n mp --target android-26 --abi "default/x86"
  - emulator -avd mp -noskin -no-boot-anim -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb shell input keyevent 1 &

script:
  - android list target
  - ./gradlew --info connectedAndroidTest
  - ./gradlew --info androidJavadocs
